language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script: python -m unittest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eyougo
  password:
    secure: m88mWSquo9Axhg8h92yREzyb2OwPTBJmpkrmko55OaXhIZKrdfovlMEua8bPuUMeSTiFUneOZDQ27tQc8DqdlJ+IoWx4nTR0TbYpCK0zq4W0pFCQOzSiKUnjGLBjXRkisLbzIZU4JcGDEzF+VJoP2fB12W+LyjvBJURnOqFuninTDo9EImKmRLCq60MfPQZmt/SSZ+szAlCTl9EJcY/mxrGsZusfiZ6NAsmtSa9iYY26+c+Jw9ci44Ht7wj4eM7bV3Sqvn/T7HytOeDCjEDAxkyopWH4QUAEMBFjdMX0GeVd5yEa3tjoD1cQaMdAwq7yIb/3ACWFd6c0uoSqWBOiguLnaHXqXvOgmV8OD48Nhx4DgMYoXPcCokOqaLy9jlAIqEWVKmf+Yp2fWMrwAVUn5wQPh7Z5dCZ75GuHn/gTSV4arQnCmBhAYFoFrV+T4mwoy+xvvMBEExHoUmlq9+kPwQdx3QXQhwUI6+4kOHFrAm9Ak9sNqHXHcn6IvKUZdSmLda3rTEnuwgDIPIOa8a0jahKfmeuneGC8b/J9qSrun35Umz3OG2Lt7BJKPM0kxQPlSZ0s9gi8CTlmOL9CHN6nVkGIb34NP6n5XLO6Va6aYuwUUqru8+4hDw3T+E2sRlJs5DPhsCldJ3zIDhU60ZwIrQPWTlm34uZ2D1KBG4Xj+6Q=
  true:
    python: 3.6
    tags: true
    branch: master
