language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script: python -m unittest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eyougo
  password:
    secure: V0izemBvcw5zQ7fbMmCczVpKEUKfXZxqA8oStjW3COc9BazWjdMBvS3BhS+Izh2xT/VaXuN++oFtsnJiflaDjGqaFf+ngGspitBVnuXOuElsgyyaUlGvNb0fIqiJvyazNagcE9PgiSRVCYyGRp92ZwV/JcbiOXu1XeIV43H+I3qKah39ai063jM7ok0NwmIoQWv62RX3+4qepPbOzX3j0ikks70d787t5pX3z4uL4iPtnJoj/KkHWyaBYw1tUZNQcYXC9fPVZiQLE80xQ1cC+4flKadlk2F4880zzo1/pqjh82ByXgcMVD0B7lSra3KzFQwy5KsUCaJZShOE95xZkMkdlkS32RHclR286nzlOMt7CH+H734Xy9jVYS9L7IM5u/18MA5LNuzdtYEfEdZJQ45U6U5/xHA4A+TjotkGhThc72GIfCYki53XA/snaESAb1KnXyQq2IpXg0MHv/GkPy4i2HOwbUCiiHDSAEp16kHax23ZpxLhXByUZTm526f8Xsw/LK+GuBStjYfXLkOjGCtTXfrxdpz1SsyJzpH0JG1Px0Gk3Y85NkI4DEiQmDeeUkcA5ZARPNWBsibBY4FW6kICGDnAEGc5fOWupJ6xProN87Ka4UAND37f56Wc10WyiK0fqYBRjDhIPEnNed4OHS238z6m5chlpHc62e9jUeo=
  true:
    python: 3.6
    branch: master
