language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script: python -m unittest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eyougo
  password:
    secure: E20XGEaBMK5edn+2yqV+vM2KEkWMLmOxo5iDS4xmB4cAgEguyENFKN3HIkdEtAlGH4YqX/qWTfOLrkFfRH5MTQo88N3hrXWeuYIy650d89crbY3WHQzXfDTD2MXrHhpSqCLgPcN/fLEy8Y6q6fHVvO7wSyPtVKBMx2DLDH91H3N5rIha5kBWqoZzs0eerRGYcnCqIzq322GAzySoASFDsriXA//kQzRK1YiDqIGUZ2HBUk7lNcdNvOI1TrafS6Vw/RRbyUuu8t0NM6GWyLor4fesAQaoL8p9MW0vQXqB2BvH2LbEhfLegeJGIfnBYsgsLCmONHqCDcGEnSzNtgSpBLgX61uufblUEMYjTldK03hyDv5okP4TMcSlK5u0gawQHe/3BuxL25QSGAQwoZUWAcBrXLyqByjJqbgfecmUxL/S6O+xfjpDfrFncaQv/qCNJCHDEyG40rMsv+hWzZQ/oNhapfCbD1cwIP2ISZHXim8lR9pE/rNW6abqhz+PdaHd2ZLqJM4j7xo/DR3IXFsC7vUY3hfo0RkyC3FnjgPD0hIb5cVI8QYx5UF3oJGJEgIf1G3cb9CpMiTaezWa8S042nCpbmZ3kCsojnWvrVyUYvWU9R6+hbRDl28BAIYyW2ueXJGKh2upB5mydftDquUD50LoAT896SU90I4MDS0j3hA=
  true:
    python: 3.6
    branch: master
