language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
script: python -m unittest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: eyougo
  password:
    secure: wA4Cz4Re8Wm3VXK1NWX4b5mILJEfHd69alBAq0qftfFmgksGn2Zd5+GS9tbydnACil45MjH+h7tjn+eDDNy0LOHhOErCvs+BKqPLWW0ebN9E5OfNB0LwK55tPOS8Y2HYSNlB5qm/PmmcW2bT6jDSw0PYgkwdmMBsHZiBgACcreIBhFrU1mls2SBLlN6Nq17Ddbpqlfeiq6092nG7NnHJBUFzUi8ogxlMR+vteX/+yUWG/jxMPO4wh1JS62XbbxI8i33g3tY4CLgaez2lSAQIQeV8rreLkR52yhQ6/PnOzAHDnrbQEpIHUfEkOG0YXFx3YLpSS/M1kfAqQlarvwroiKCafD+UgmWgNIFJ1K9UQbZZb7LsRXylUeM3nDlnjhL2rGiWpjvqRmPFQqCWM7JRIEkwldLGANMj9AAbqWDNTRW+sgcVgV/Sn00JOS++5klXW4tGBSp614vqd6CjN6Qz3Ap1bTP2yqQu4v0oIySjLyAhB41w01SBBqgL2tHCheqVQq1rpACDV03zIkUppOrK1CvCH0p42ffMidYY2Fm9QTUW6k/YmkODdJ+83fQc2cWiXEQ+7kvfjesDJbKjWFpRAThQbmjishs1jZPQAB5bgNz4L56IAQ50IKcazYwZOUdhlogshuLSWR8L0auPQhmCebi9RE81XXK3ROFJwCx1GUk=
  on:
    python: 3.6
    branch: master
