language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install -r requirements.txt
script: python -m unittest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bohanzhang
  password:
    secure: Vx8bHFgM9rFjTrpCRSQBYmg+lm2AXznRYWvE9+lzAKMTCkVUbX9xp9U62ZdWdH2yawcEN5V5JpfG3GbTV/DbuOTTuWzjUa9PYXvHt+TmoenME5vCjhxPiwfS3xDTrcwq+o0JEhzDFNgg+MMCcaeozL3RL1YizgqwhfY10FbqSK3KMnkf03WYiB2L5F2kwv2OruyeWpEOn4szZL+QlVHFFvwGfuMc4BOIqrH4XLm29sWFbRe6DXginLqPRhEE3dB5LHcvebR9oNCWCPdKAADBlZBGnDyREE5mzDx3pyY7u7DfroNC/yXteFaqUtOwT3o8IS18b7GFr+J2TVw9Iydt38vQxPpxAzuxWqhrbsV86VtlCP1JISEutceXyfBymzhUifQtKXD+1X7kayMLlWC1fDjcBIVT+AZ2Oh27tP0Bg7Vh5+q2ZxggxgjY1mLoz6XNL/JAjbPcEu4IW1j9QGrimh9wCpumpGlt/pg00+GEo3aqj1XvUSfso9yYs1A6lIVcttlLQZu2+aYePqi69fSuenU39SUhh1qL3BwwanV9Mo2X3qIaDAl3B1PlH71QOqQEHrhuvNSOK5193Uue27XZW5WBQJV6sa/1wnk0FdjXdv6UMzfffeK7PJ1ZcTQsomyhZT6BqNLCgTMgarGio8jM7rpXuTfk7fmT+0RvfjQfvYE=
  on:
    python: 3.6
    tags: true
    branch: master